name: First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Print a greeting
        run: echo "Hello, GitHub Actions!"

      - name: List repository files
        run: ls -la /
        
      - name: Use an environment variable
        env:
          MY_VAR: "This is a custom environment variable!"
        run: echo "The value of MY_VAR is: $MY_VAR"
